name: 😎
on:
  push:
    branches:    
      - master
jobs:
  lighthouse_ci:

    runs-on: ubuntu-latest

    steps:

      - name: git clone
        uses: actions/checkout@v1
        
      - name: setup node.js
        uses: actions/setup-node@c6fd00c
        with:
          node-version: 10.x

      - name: build
        run: npm i && npm run build

      - name: Publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          npm config set '//registry.npmjs.org/:_authToken' '${NPM_TOKEN}'
          npm publish
